### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by zagzhang** [PayasR/redbase-spatial#3]
@PayasR 
src/parse.y:77:2: error: ‘V_MBR’ does not name a type

[root@zagnix build]# make 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/sw/redbase/build
Scanning dependencies of target pf
[  2%] Building CXX object CMakeFiles/pf.dir/src/pf_buffermgr.cc.o
[  4%] Building CXX object CMakeFiles/pf.dir/src/pf_error.cc.o
[  6%] Building CXX object CMakeFiles/pf.dir/src/pf_filehandle.cc.o
[  8%] Building CXX object CMakeFiles/pf.dir/src/pf_pagehandle.cc.o
[ 10%] Building CXX object CMakeFiles/pf.dir/src/pf_hashtable.cc.o
[ 12%] Building CXX object CMakeFiles/pf.dir/src/pf_manager.cc.o
[ 14%] Building CXX object CMakeFiles/pf.dir/src/pf_statistics.cc.o
[ 16%] Building CXX object CMakeFiles/pf.dir/src/statistics.cc.o
[ 18%] Linking CXX static library libpf.a
[ 18%] Built target pf
[ 20%] [FLEX][MyScanner] Building scanner with flex 2.5.37
[ 22%] [BISON][MyParser] Building parser with bison 2.7
Scanning dependencies of target parser
[ 25%] Building CXX object CMakeFiles/parser.dir/src/nodes.cc.o
In file included from /root/sw/redbase/src/nodes.cc:16:0:
src/parse.y:77:2: error: ‘V_MBR’ does not name a type
make[2]: *** [CMakeFiles/parser.dir/src/nodes.cc.o] Error 1
make[1]: *** [CMakeFiles/parser.dir/all] Error 2
make: *** [all] Error 2

**Comment by PayasR** [comment]
Thank you @zagnix :)
I just put up a patch. But this code is just the starter code for an assignment, and intentionally incomplete. May I know what you're using this for?
